version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: pg_admin_db_container
    environment:
      POSTGRES_DB: pg_admin_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U admin -d pg_admin_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pg-admin-service:
    build: .
    container_name: pg_admin_service_container
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://postgres:5432/pg_admin_db
      DB_USERNAME: admin
      DB_PASSWORD: password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pg-network

volumes:
  postgres_data:


networks:
  pg-network:
